### ISSUE TITLE
Will this work on Windows?

### ISSUE THREAD

**Issue by tyeeman** [dagostinelli/spoonbill#1]
I would sure like to try this out but on Windows I can't run make files, true? Or do I need to. Can I just run setup.py?

**Comment by djacobson** [comment]
Fyi, there are several options for installing and making `make` available in the Windows console:

https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows/32127632#32127632

**Comment by tyeeman** [comment]
Good, I got it. Now I don't see any install instructions. I'm no coder but if all I do is run "make" in the cloned directory, is that it?

**Comment by dagostinelli** [comment]
What you are after is the `setup.py`. The Makefile is actually for spoonbill development. 

You wrote that you aren't a coder, but you figured out how to get into GitHub and asked about the setup.py and Makefiles.  I'd say that you are already on the right path. :+1: 

Spoonbill has been tested in Windows using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/faq).  But normally that's not what people mean.  The normal Windows hasn't been tested with Spoonbill yet.  If you do it, write back because I want to hear about it.

Lastly, you're right about instructions.  I do need to make a nice sample web site for this...

**Comment by dagostinelli** [comment]
The ideas from this issue are now documented in two new issues. Closing.
